name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ["main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: UniverseFly/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: UniverseFly
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Chicago

          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_recent_categories: programming
          plugin_languages_sections: recently-used
          plugin_languages_details: bytes-size, percentage

          plugin_repositories: yes
          plugin_repositories_order: pinned, starred, random
          plugin_repositories_pinned: 3
